services:
  web:
    build: .
    container_name: sales_web
    environment:
      FLASK_ENV: development
      SECRET_KEY: jtyjxdnjncdkm
      DATABASE_URL: postgresql://postgres:deno0707@37.60.242.201:5432/sales_management
    ports:
      - "5000:5000"
    # Optional: mount app/static to provide logo.jpg without rebuilding
    # volumes:
    #   - ./app/static:/app/app/static:ro
